apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home-pv
  namespace: kube-jenkins
spec:
  capacity:
    storage: 50Gi  #容量
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/gdmt/mastercom/mtex/jenkins/jenkins-nexus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  namespace: kube-jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi