apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: kube-jenkins
spec:
  selector:
    app: jenkins-deploy
  ports:
    - port: 8080
      name: jenkins-web
      targetPort: 8080
      nodePort: 31442
    - port: 50000
      name: jenkins-agent
      targetPort: 50000
      nodePort: 30005
  type: NodePort