apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-account
  namespace: kube-jenkins
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: jenkins-role
  namespace: kube-jenkins
rules:
  - verbs: ["create","delete","get","list","patch","update","watch"]
    apiGroups: [""]
    resources: ["pods"]
  - verbs: ["create","delete","get","list","patch","update","watch"]
    apiGroups: [""]
    resources: ["pods/exec"]
  - verbs: ["get","list","watch"]
    apiGroups: [""]
    resources: ["pods/log"]
  - verbs: ["get"]
    apiGroups: [""]
    resources: ["secrets"]
---
  apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: jenkins-roleBinding
    namespace: kube-jenkins
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: jenkins-role
  subjects:
    - kind: ServiceAccount
      name: jenkins-account
      namespace: kube-jenkins
  